"""Initial schema - Stage 4-7 models

Revision ID: 83b280b69e5f
Revises: 
Create Date: 2026-08-22 03:36:11.303502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83b280b69e5f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_employees',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('agent_type', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_ai_employees_department', 'ai_employees', ['department'], unique=False)
    op.create_index('idx_ai_employees_position', 'ai_employees', ['position'], unique=False)
    op.create_index('idx_ai_employees_status', 'ai_employees', ['status'], unique=False)
    op.create_table('business_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('assigned_employee_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_by', sa.String(length=36), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_business_tasks_assigned_employee_id', 'business_tasks', ['assigned_employee_id'], unique=False)
    op.create_index('idx_business_tasks_domain', 'business_tasks', ['domain'], unique=False)
    op.create_index('idx_business_tasks_priority', 'business_tasks', ['priority'], unique=False)
    op.create_index('idx_business_tasks_status', 'business_tasks', ['status'], unique=False)
    op.create_table('company_brain_entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('relationships', sa.JSON(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_company_brain_company_id', 'company_brain_entities', ['company_id'], unique=False)
    op.create_index('idx_company_brain_entity_type', 'company_brain_entities', ['entity_type'], unique=False)
    op.create_index('idx_company_brain_name', 'company_brain_entities', ['name'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_created_at', 'documents', ['created_at'], unique=False)
    op.create_index('idx_documents_created_by', 'documents', ['created_by'], unique=False)
    op.create_index('idx_documents_file_type', 'documents', ['file_type'], unique=False)
    op.create_index('idx_documents_status', 'documents', ['status'], unique=False)
    op.create_table('memories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('memory_type', sa.String(length=50), nullable=False),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_memories_agent_id', 'memories', ['agent_id'], unique=False)
    op.create_index('idx_memories_importance', 'memories', ['importance'], unique=False)
    op.create_index('idx_memories_memory_type', 'memories', ['memory_type'], unique=False)
    op.create_index('idx_memories_user_id', 'memories', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('assigned_to', sa.JSON(), nullable=True),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=True),
    sa.Column('parent_task_id', sa.String(length=36), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_creator_id', 'tasks', ['creator_id'], unique=False)
    op.create_index('idx_tasks_priority', 'tasks', ['priority'], unique=False)
    op.create_index('idx_tasks_status', 'tasks', ['status'], unique=False)
    op.create_index('idx_tasks_task_type', 'tasks', ['task_type'], unique=False)
    op.create_index('idx_tasks_workflow_id', 'tasks', ['workflow_id'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflows_created_by', 'workflows', ['created_by'], unique=False)
    op.create_index('idx_workflows_enabled', 'workflows', ['enabled'], unique=False)
    op.create_index('idx_workflows_name', 'workflows', ['name'], unique=False)
    op.create_table('employee_costs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('api_calls', sa.Integer(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['ai_employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_employee_costs_employee_id', 'employee_costs', ['employee_id'], unique=False)
    op.create_index('idx_employee_costs_period', 'employee_costs', ['period_start', 'period_end'], unique=False)
    op.create_table('employee_performance',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('tasks_completed', sa.Integer(), nullable=False),
    sa.Column('tasks_failed', sa.Integer(), nullable=False),
    sa.Column('avg_execution_time_seconds', sa.Float(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('user_rating', sa.Float(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['ai_employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_employee_performance_employee_id', 'employee_performance', ['employee_id'], unique=False)
    op.create_index('idx_employee_performance_period', 'employee_performance', ['period_start', 'period_end'], unique=False)
    op.create_table('task_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('execution_time_seconds', sa.Float(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_results_success', 'task_results', ['success'], unique=False)
    op.create_index('idx_task_results_task_id', 'task_results', ['task_id'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_executions_status', 'workflow_executions', ['status'], unique=False)
    op.create_index('idx_workflow_executions_user_id', 'workflow_executions', ['user_id'], unique=False)
    op.create_index('idx_workflow_executions_workflow_id', 'workflow_executions', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_workflow_executions_workflow_id', table_name='workflow_executions')
    op.drop_index('idx_workflow_executions_user_id', table_name='workflow_executions')
    op.drop_index('idx_workflow_executions_status', table_name='workflow_executions')
    op.drop_table('workflow_executions')
    op.drop_index('idx_task_results_task_id', table_name='task_results')
    op.drop_index('idx_task_results_success', table_name='task_results')
    op.drop_table('task_results')
    op.drop_index('idx_employee_performance_period', table_name='employee_performance')
    op.drop_index('idx_employee_performance_employee_id', table_name='employee_performance')
    op.drop_table('employee_performance')
    op.drop_index('idx_employee_costs_period', table_name='employee_costs')
    op.drop_index('idx_employee_costs_employee_id', table_name='employee_costs')
    op.drop_table('employee_costs')
    op.drop_index('idx_workflows_name', table_name='workflows')
    op.drop_index('idx_workflows_enabled', table_name='workflows')
    op.drop_index('idx_workflows_created_by', table_name='workflows')
    op.drop_table('workflows')
    op.drop_index('idx_tasks_workflow_id', table_name='tasks')
    op.drop_index('idx_tasks_task_type', table_name='tasks')
    op.drop_index('idx_tasks_status', table_name='tasks')
    op.drop_index('idx_tasks_priority', table_name='tasks')
    op.drop_index('idx_tasks_creator_id', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('idx_memories_user_id', table_name='memories')
    op.drop_index('idx_memories_memory_type', table_name='memories')
    op.drop_index('idx_memories_importance', table_name='memories')
    op.drop_index('idx_memories_agent_id', table_name='memories')
    op.drop_table('memories')
    op.drop_index('idx_documents_status', table_name='documents')
    op.drop_index('idx_documents_file_type', table_name='documents')
    op.drop_index('idx_documents_created_by', table_name='documents')
    op.drop_index('idx_documents_created_at', table_name='documents')
    op.drop_table('documents')
    op.drop_index('idx_company_brain_name', table_name='company_brain_entities')
    op.drop_index('idx_company_brain_entity_type', table_name='company_brain_entities')
    op.drop_index('idx_company_brain_company_id', table_name='company_brain_entities')
    op.drop_table('company_brain_entities')
    op.drop_index('idx_business_tasks_status', table_name='business_tasks')
    op.drop_index('idx_business_tasks_priority', table_name='business_tasks')
    op.drop_index('idx_business_tasks_domain', table_name='business_tasks')
    op.drop_index('idx_business_tasks_assigned_employee_id', table_name='business_tasks')
    op.drop_table('business_tasks')
    op.drop_index('idx_ai_employees_status', table_name='ai_employees')
    op.drop_index('idx_ai_employees_position', table_name='ai_employees')
    op.drop_index('idx_ai_employees_department', table_name='ai_employees')
    op.drop_table('ai_employees')
    # ### end Alembic commands ###
