"""add_supplier_intelligence_tables

Revision ID: bc4420b32d53
Revises: 83b280b69e5f
Create Date: 2026-08-23 03:40:08.863227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc4420b32d53'
down_revision: Union[str, Sequence[str], None] = '83b280b69e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False, comment='供应商ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='供应商名称'),
    sa.Column('legal_name', sa.String(length=255), nullable=True, comment='法定名称（全称）'),
    sa.Column('code', sa.String(length=50), nullable=True, comment='供应商编码'),
    sa.Column('country', sa.String(length=100), nullable=False, comment='国家'),
    sa.Column('province', sa.String(length=100), nullable=True, comment='省份/州'),
    sa.Column('city', sa.String(length=100), nullable=True, comment='城市'),
    sa.Column('district', sa.String(length=100), nullable=True, comment='区/县'),
    sa.Column('address', sa.Text(), nullable=True, comment='详细地址'),
    sa.Column('postal_code', sa.String(length=20), nullable=True, comment='邮政编码'),
    sa.Column('business_type', sa.Enum('MANUFACTURER', 'TRADING', 'AGENT', 'DISTRIBUTOR', 'SERVICE', name='businesstype'), nullable=False, comment='企业类型'),
    sa.Column('product_category', sa.String(length=255), nullable=True, comment='主营产品类别'),
    sa.Column('industry', sa.String(length=100), nullable=True, comment='所属行业'),
    sa.Column('established_date', sa.DateTime(), nullable=True, comment='成立日期'),
    sa.Column('registered_capital', sa.Float(), nullable=True, comment='注册资本（USD）'),
    sa.Column('employee_count', sa.Integer(), nullable=True, comment='员工数量'),
    sa.Column('annual_revenue', sa.Float(), nullable=True, comment='年营业额（USD）'),
    sa.Column('phone', sa.String(length=50), nullable=True, comment='公司电话'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='公司邮箱'),
    sa.Column('website', sa.String(length=500), nullable=True, comment='公司网站'),
    sa.Column('wechat', sa.String(length=100), nullable=True, comment='微信号'),
    sa.Column('whatsapp', sa.String(length=100), nullable=True, comment='WhatsApp'),
    sa.Column('credit_rating', sa.String(length=10), nullable=True, comment='信用评级（AAA, AA, A, BBB, BB, B, C）'),
    sa.Column('risk_score', sa.Float(), nullable=True, comment='综合风险评分 (0-100)'),
    sa.Column('has_iso9001', sa.Boolean(), nullable=True, comment='是否有 ISO 9001 认证'),
    sa.Column('has_iso14001', sa.Boolean(), nullable=True, comment='是否有 ISO 14001 认证'),
    sa.Column('has_export_license', sa.Boolean(), nullable=True, comment='是否有出口许可证'),
    sa.Column('cooperation_years', sa.Integer(), nullable=True, comment='合作年限'),
    sa.Column('total_orders', sa.Integer(), nullable=True, comment='历史订单总数'),
    sa.Column('total_amount', sa.Float(), nullable=True, comment='历史交易总额（USD）'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BLACKLIST', 'PENDING', name='supplierstatus'), nullable=False, comment='供应商状态'),
    sa.Column('is_verified', sa.Boolean(), nullable=True, comment='是否已实地验厂'),
    sa.Column('description', sa.Text(), nullable=True, comment='供应商简介'),
    sa.Column('notes', sa.Text(), nullable=True, comment='内部备注'),
    sa.Column('tags', sa.String(length=500), nullable=True, comment='标签（逗号分隔）'),
    sa.Column('source', sa.String(length=100), nullable=True, comment='数据来源（alibaba, made-in-china, manual）'),
    sa.Column('source_url', sa.String(length=1000), nullable=True, comment='来源URL'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('last_contacted_at', sa.DateTime(), nullable=True, comment='最后联系时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_city'), 'suppliers', ['city'], unique=False)
    op.create_index(op.f('ix_suppliers_code'), 'suppliers', ['code'], unique=True)
    op.create_index(op.f('ix_suppliers_country'), 'suppliers', ['country'], unique=False)
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.create_index(op.f('ix_suppliers_industry'), 'suppliers', ['industry'], unique=False)
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_index(op.f('ix_suppliers_product_category'), 'suppliers', ['product_category'], unique=False)
    op.create_index(op.f('ix_suppliers_status'), 'suppliers', ['status'], unique=False)
    op.create_table('supplier_certificates',
    sa.Column('id', sa.Integer(), nullable=False, comment='证书ID'),
    sa.Column('supplier_id', sa.Integer(), nullable=False, comment='供应商ID'),
    sa.Column('certificate_type', sa.Enum('ISO9001', 'ISO14001', 'CE', 'FDA', 'ROHS', 'BUSINESS_LICENSE', 'EXPORT_LICENSE', 'OTHER', name='certificatetype'), nullable=False, comment='证书类型'),
    sa.Column('certificate_name', sa.String(length=255), nullable=False, comment='证书名称'),
    sa.Column('certificate_number', sa.String(length=255), nullable=True, comment='证书编号'),
    sa.Column('issuing_authority', sa.String(length=255), nullable=True, comment='颁发机构'),
    sa.Column('issuing_country', sa.String(length=100), nullable=True, comment='颁发国家'),
    sa.Column('issue_date', sa.DateTime(), nullable=True, comment='颁发日期'),
    sa.Column('expiry_date', sa.DateTime(), nullable=True, comment='到期日期'),
    sa.Column('is_permanent', sa.Boolean(), nullable=True, comment='是否永久有效'),
    sa.Column('file_url', sa.String(length=1000), nullable=True, comment='证书文件URL'),
    sa.Column('file_name', sa.String(length=500), nullable=True, comment='文件名'),
    sa.Column('is_verified', sa.Boolean(), nullable=True, comment='是否已验证'),
    sa.Column('verified_at', sa.DateTime(), nullable=True, comment='验证时间'),
    sa.Column('verified_by', sa.Integer(), nullable=True, comment='验证人ID'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_certificates_certificate_type'), 'supplier_certificates', ['certificate_type'], unique=False)
    op.create_index(op.f('ix_supplier_certificates_id'), 'supplier_certificates', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_certificates_supplier_id'), 'supplier_certificates', ['supplier_id'], unique=False)
    op.create_table('supplier_contacts',
    sa.Column('id', sa.Integer(), nullable=False, comment='联系人ID'),
    sa.Column('supplier_id', sa.Integer(), nullable=False, comment='供应商ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='联系人姓名'),
    sa.Column('name_en', sa.String(length=100), nullable=True, comment='英文姓名'),
    sa.Column('position', sa.String(length=100), nullable=True, comment='职位'),
    sa.Column('department', sa.String(length=100), nullable=True, comment='部门'),
    sa.Column('phone', sa.String(length=50), nullable=True, comment='电话'),
    sa.Column('mobile', sa.String(length=50), nullable=True, comment='手机'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='邮箱'),
    sa.Column('wechat', sa.String(length=100), nullable=True, comment='微信号'),
    sa.Column('whatsapp', sa.String(length=100), nullable=True, comment='WhatsApp'),
    sa.Column('skype', sa.String(length=100), nullable=True, comment='Skype'),
    sa.Column('is_primary', sa.Boolean(), nullable=True, comment='是否主要联系人'),
    sa.Column('is_decision_maker', sa.Boolean(), nullable=True, comment='是否决策人'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('last_contacted_at', sa.DateTime(), nullable=True, comment='最后联系时间'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_contacts_id'), 'supplier_contacts', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_contacts_supplier_id'), 'supplier_contacts', ['supplier_id'], unique=False)
    op.create_table('supplier_risk_assessments',
    sa.Column('id', sa.Integer(), nullable=False, comment='评估ID'),
    sa.Column('supplier_id', sa.Integer(), nullable=False, comment='供应商ID'),
    sa.Column('compliance_score', sa.Float(), nullable=True, comment='合规评分 (法律、资质、认证)'),
    sa.Column('financial_score', sa.Float(), nullable=True, comment='财务评分 (注册资本、营收、信用)'),
    sa.Column('delivery_score', sa.Float(), nullable=True, comment='履约评分 (交货准时率、合同执行)'),
    sa.Column('quality_score', sa.Float(), nullable=True, comment='质量评分 (产品质量、客户投诉)'),
    sa.Column('communication_score', sa.Float(), nullable=True, comment='沟通评分 (响应速度、服务态度)'),
    sa.Column('overall_score', sa.Float(), nullable=True, comment='综合评分 (0-100)'),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), nullable=False, comment='风险等级'),
    sa.Column('strengths', sa.Text(), nullable=True, comment='优势（JSON 数组）'),
    sa.Column('weaknesses', sa.Text(), nullable=True, comment='劣势（JSON 数组）'),
    sa.Column('opportunities', sa.Text(), nullable=True, comment='机会（JSON 数组）'),
    sa.Column('threats', sa.Text(), nullable=True, comment='威胁（JSON 数组）'),
    sa.Column('swot_summary', sa.Text(), nullable=True, comment='SWOT 分析总结'),
    sa.Column('risk_report', sa.Text(), nullable=True, comment='风险评估报告（Markdown）'),
    sa.Column('recommendations', sa.Text(), nullable=True, comment='建议（JSON 数组）'),
    sa.Column('assessment_date', sa.DateTime(), nullable=False, comment='评估日期'),
    sa.Column('assessor_id', sa.Integer(), nullable=True, comment='评估人ID（用户或AI Agent）'),
    sa.Column('assessment_method', sa.String(length=50), nullable=True, comment='评估方式（manual=人工, ai=AI自动, hybrid=混合）'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_risk_assessments_id'), 'supplier_risk_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_risk_assessments_risk_level'), 'supplier_risk_assessments', ['risk_level'], unique=False)
    op.create_index(op.f('ix_supplier_risk_assessments_supplier_id'), 'supplier_risk_assessments', ['supplier_id'], unique=False)
    # SQLite doesn't support ALTER COLUMN - skip this operation
    pass  # op.alter_column('ai_employees', 'agent_type', existing_type=sa.VARCHAR(length=100), nullable=True)
    op.add_column('company_brain_facts', sa.Column('supersedes', sa.String(length=36), nullable=True))
    op.add_column('company_brain_facts', sa.Column('superseded_by', sa.String(length=36), nullable=True))
    op.add_column('memories', sa.Column('session_id', sa.String(length=255), nullable=True))
    op.add_column('memories', sa.Column('task_id', sa.String(length=255), nullable=True))
    op.add_column('memories', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memories', 'expires_at')
    op.drop_column('memories', 'task_id')
    op.drop_column('memories', 'session_id')
    op.drop_column('company_brain_facts', 'superseded_by')
    op.drop_column('company_brain_facts', 'supersedes')
    # SQLite doesn't support ALTER COLUMN - skip this operation
    pass  # op.alter_column('ai_employees', 'agent_type', existing_type=sa.VARCHAR(length=100), nullable=False)
    op.drop_index(op.f('ix_supplier_risk_assessments_supplier_id'), table_name='supplier_risk_assessments')
    op.drop_index(op.f('ix_supplier_risk_assessments_risk_level'), table_name='supplier_risk_assessments')
    op.drop_index(op.f('ix_supplier_risk_assessments_id'), table_name='supplier_risk_assessments')
    op.drop_table('supplier_risk_assessments')
    op.drop_index(op.f('ix_supplier_contacts_supplier_id'), table_name='supplier_contacts')
    op.drop_index(op.f('ix_supplier_contacts_id'), table_name='supplier_contacts')
    op.drop_table('supplier_contacts')
    op.drop_index(op.f('ix_supplier_certificates_supplier_id'), table_name='supplier_certificates')
    op.drop_index(op.f('ix_supplier_certificates_id'), table_name='supplier_certificates')
    op.drop_index(op.f('ix_supplier_certificates_certificate_type'), table_name='supplier_certificates')
    op.drop_table('supplier_certificates')
    op.drop_index(op.f('ix_suppliers_status'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_product_category'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_industry'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_country'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_code'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_city'), table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###

